#!/usr/bin/env python3
"""Agent Factory — Generate multi-agent AI systems from a YAML batch spec.

Usage:
    factory specs/batch.yaml
    python -m gatekeeper_eos_v6 specs/batch.yaml

Supports two output targets (OpenAI Agents SDK, LangGraph) and eight
orchestration patterns (handoffs, agents_as_tools, router_manager,
supervisor_workers, chain, broadcast, reflection, debate).  Each system
is rendered from Jinja2 templates and placed in its own folder under
generated/.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
# factory.py lives at src/gatekeeper_eos_v6/factory.py
# Project root is three levels up
HERE = Path(__file__).resolve().parent.parent.parent
TEMPLATES_DIR = HERE / "templates"
GENERATED_DIR = HERE / "generated"

SUPPORTED_TARGETS = {"openai", "langgraph"}
SUPPORTED_PATTERNS = {"handoffs", "agents_as_tools", "router_manager", "supervisor_workers", "chain", "broadcast", "reflection", "debate"}


# ---------------------------------------------------------------------------
# Spec loading & validation
# ---------------------------------------------------------------------------
def load_spec(path: str) -> dict:
    """Load and return the YAML batch spec from *path*."""
    with open(path) as f:
        spec = yaml.safe_load(f)
    return spec


def validate_spec(spec: dict) -> list[str]:
    """Return a list of validation errors (empty = valid)."""
    errors: list[str] = []
    systems = spec.get("systems", [])
    if not systems:
        errors.append("spec must contain at least one system under 'systems'")
        return errors

    for i, sys_def in enumerate(systems):
        prefix = f"systems[{i}]"
        if "name" not in sys_def:
            errors.append(f"{prefix}: missing required field 'name'")
        if sys_def.get("target") not in SUPPORTED_TARGETS:
            errors.append(f"{prefix}: target must be one of {SUPPORTED_TARGETS}")
        if sys_def.get("pattern") not in SUPPORTED_PATTERNS:
            errors.append(f"{prefix}: pattern must be one of {SUPPORTED_PATTERNS}")
        if "agents" not in sys_def or not isinstance(sys_def["agents"], list):
            errors.append(f"{prefix}: must have at least one agent in 'agents' list")

    return errors


# ---------------------------------------------------------------------------
# Documentation generators (no template files needed)
# ---------------------------------------------------------------------------
def _generate_system_config(system: dict) -> str:
    """Generate a system.yaml config file with the original spec params."""
    return yaml.dump(system, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _generate_readme(system: dict) -> str:
    """Generate a README.md for a single generated system."""
    name = system["name"]
    target = system["target"]
    pattern = system["pattern"]
    desc = system.get("description", "").strip()

    agents_str = "\n".join(
        f"  - **{a['name']}**: {a['instructions'][:80]}..."
        for a in system.get("agents", [])
    )

    return f"""# {name}

{desc}

## Overview

| Attribute | Value |
|-----------|-------|
| **Target** | {target} |
| **Pattern** | {pattern} |
| **Model** | {system.get('model', 'gpt-4o')} |
| **Agents** | {len(system.get('agents', []))} |

## Agents

{agents_str}

## Quickstart

1. Set your `OPENAI_API_KEY`:
   ```bash
   export OPENAI_API_KEY=sk-...
   ```

2. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

3. Run the system:
   ```bash
   python main.py
   ```

   You can also pass input via the `USER_INPUT` environment variable:
   ```bash
   USER_INPUT="Your question here" python main.py
   ```

## Generated By

[Agent Factory](https://github.com/your-org/gatekeeper-eos-v6) —
template-based multi-agent system generator.
"""


def _generate_agents_md(system: dict) -> str:
    """Generate an AGENTS.md with agent specifications for the system."""
    target = system["target"]
    pattern = system["pattern"]

    agents_str = ""
    for a in system.get("agents", []):
        agents_str += f"""
## {a['name']}

- **Role**: {a['name'].replace('_', ' ').title()}
- **Instructions**: {a['instructions']}
- **Pattern integration**: See {pattern} pattern in {target} target.

"""

    return f"""# {system['name']} — Agent Specifications

Generated {len(system.get('agents', []))} agent(s) for `{target}` / `{pattern}`.

{agents_str}
## Architecture

This system uses the **{pattern.replace('_', ' ').title()}** pattern
on the **{target.title()}** platform.

Refer to `main.py` for the full implementation.
"""


# ---------------------------------------------------------------------------
# Code generation & output
# ---------------------------------------------------------------------------
def _render_template(env: Environment, template_path: str, system: dict) -> str:
    """Render a Jinja2 template to a string."""
    template = env.get_template(template_path)
    return template.render(system=system)


def generate_system(system: dict, env: Environment) -> Path:
    """Generate one agentic system into a sub-folder of *GENERATED_DIR*.

    Returns the path to the created folder.
    """
    name = system["name"]
    target = system["target"]
    pattern = system["pattern"]

    out_dir = GENERATED_DIR / name
    out_dir.mkdir(parents=True, exist_ok=True)

    # Render main.py from Jinja2 template
    main_code = _render_template(env, f"{target}/{pattern}/main.py.j2", system)
    (out_dir / "main.py").write_text(main_code)

    # Render requirements.txt
    reqs = _render_template(env, f"{target}/{pattern}/requirements.txt.j2", system)
    (out_dir / "requirements.txt").write_text(reqs)

    # Generate documentation
    (out_dir / "README.md").write_text(_generate_readme(system))
    (out_dir / "AGENTS.md").write_text(_generate_agents_md(system))

    # Write the system spec as a shareable config file
    (out_dir / "system.yaml").write_text(_generate_system_config(system))

    return out_dir


def generate_all(spec: dict, env: Environment) -> list[Path]:
    """Generate all systems defined in *spec* and return their paths."""
    generated: list[Path] = []
    for system in spec.get("systems", []):
        out = generate_system(system, env)
        generated.append(out)
        print(f"  ✓ {system['name']} → {out}")
    return generated


# ---------------------------------------------------------------------------
# Preview mode
# ---------------------------------------------------------------------------
def preview_all(
    spec: dict,
    output_dir: Path,
    env: Environment | None = None,
    verbose: bool = False,
) -> None:
    """Print a tree of what would be generated without writing any files.

    When *verbose* is True and *env* is provided, renders each template
    in-memory and shows line counts and byte sizes alongside the file tree.
    """
    for system in spec.get("systems", []):
        name = system["name"]
        target = system["target"]
        pattern = system["pattern"]

        print(f"\n  {output_dir / name}/")

        if verbose and env:
            main_code = _render_template(env, f"{target}/{pattern}/main.py.j2", system)
            reqs_code = _render_template(env, f"{target}/{pattern}/requirements.txt.j2", system)
            readme_code = _generate_readme(system)
            agents_code = _generate_agents_md(system)
            config_code = _generate_system_config(system)

            files_info = [
                ("main.py", len(main_code.splitlines()), len(main_code)),
                ("requirements.txt", len(reqs_code.splitlines()), len(reqs_code)),
                ("README.md", len(readme_code.splitlines()), len(readme_code)),
                ("AGENTS.md", len(agents_code.splitlines()), len(agents_code)),
                ("system.yaml", len(config_code.splitlines()), len(config_code)),
            ]

            for i, (fname, lines, size) in enumerate(files_info):
                prefix = "├── " if i < 4 else "└── "
                print(f"  {prefix}{fname}  ({lines} lines, {size} B)")
        else:
            print(f"  ├── main.py")
            print(f"  ├── requirements.txt")
            print(f"  ├── README.md")
            print(f"  ├── AGENTS.md")
            print(f"  └── system.yaml")

        print(f"\n    target: {target}  |  pattern: {pattern}  |  agents: {len(system.get('agents', []))}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Agent Factory — Generate multi-agent AI systems from YAML specs.",
    )
    parser.add_argument(
        "spec",
        help="Path to the batch YAML specification file (e.g. specs/batch.yaml)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=str(GENERATED_DIR),
        help=f"Output directory (default: {GENERATED_DIR})",
    )
    parser.add_argument(
        "--list-patterns",
        action="store_true",
        help="List available targets and patterns, then exit",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Preview generated folder structure without writing any files",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Show detailed file stats in preview mode (line counts, sizes)",
    )
    return parser.parse_args(argv)


def list_patterns() -> None:
    """Print available targets and patterns."""
    print("Available targets:", ", ".join(sorted(SUPPORTED_TARGETS)))
    print("Available patterns:", ", ".join(sorted(SUPPORTED_PATTERNS)))


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.list_patterns:
        list_patterns()
        return 0

    spec_path = Path(args.spec)
    if not spec_path.exists():
        print(f"Error: spec file not found: {spec_path}", file=sys.stderr)
        return 1

    # Load & validate
    spec = load_spec(str(spec_path))
    errors = validate_spec(spec)
    if errors:
        print("Validation errors:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    # Set up Jinja2 environment
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html", "xml"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )

    # Preview or generate
    output_dir = Path(args.output)
    if args.preview:
        label = "Previewing" if not args.verbose else "Verbose previewing"
        print(f"{label} {len(spec['systems'])} system(s) in {output_dir}/ …")
        preview_all(spec, output_dir, env=env, verbose=args.verbose)
        print(f"\n(No files written — use without --preview to generate)")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Generating {len(spec['systems'])} system(s) …")
    results = generate_all(spec, env)
    print(f"\nDone — {len(results)} system(s) generated in {output_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
